# 데이터분석프로그래밍 3주차 실습

## 실습 시작 전 유의사항

※ 상단 메뉴에서 '**파일 - 드라이브에 사본 저장**' 진행 후 시작하세요.\
※ 프로젝트 제목 뒤에 본인의 이름과 학번을 작성하세요. `ex) DataAnalysisProgramming_#01_202312345_정재호.ipynb`

## 실습 개요
- Python 자료구조
  - dict
  - 리스트 인덱싱과 슬라이싱
  - 2차원 리스트의 슬라이싱
- Numpy Array
  - Numpy의 슬라이싱
  - array와 list의 연산 차이

---

## 자료구조 dict
dict는 key와 value의 쌍으로 이뤄진 자료구조입니다.

dict[key]를 통해 특정 key와 매핑된 value에 접근할 수 있습니다.

해당 실습에서는 dict를 이용해 각 과일이 몇 번 언급되는지 카운팅해보도록 합시다.


In [ ]:
favorite = ["사과", "바나나", "체리", "사과", "사과", "복숭아", "바나나", "사과"]

count_dict = dict()
for fruit in favorite:
  # if fruit not in count_dict:
  #   count_dict[fruit] = 0
  # count_dict[fruit] += 1

  count_dict[fruit] = count_dict.get(fruit,0) + 1

# 각 과일마다 몇 명에 해당되는지 출력
for key, value in count_dict.items():
  print(f"[{key}]를 좋아하는 사람은 {value}명 입니다.")

[사과]를 좋아하는 사람은 4명 입니다.
[바나나]를 좋아하는 사람은 2명 입니다.
[체리]를 좋아하는 사람은 1명 입니다.
[복숭아]를 좋아하는 사람은 1명 입니다.


## 리스트 인덱싱과 슬라이싱
리스트의 원하는 요소에 접근하기 위해 인덱스를 사용하는 방법을 실습해보겠습니다.\
**`array[1]`**처럼 하나의 인덱스로 접근하는 것을 인덱싱,\
**`array[1:3]`**처럼 여러 개의 인덱스로 특정 범위에 접근하는 것을 슬라이싱이라고 합니다.

split_list(array) 함수는 임의의 리스트 array를 매개변수로 받아서\
**맨 처음 값**과 **맨 마지막 값**, 그리고 **나머지 중간 값**으로 분리해주는 함수입니다.

각 반환값에 상응하도록 올바른 인덱스를 작성해보세요.

In [ ]:
def split_list(array):
  first_element = array[0]
  last_element = array[-1]
  middle_element = array[1:-1]

  return first_element, middle_element, last_element

In [ ]:
array = [1, 2, 3, 4, 5]

# 함수의 결과값을 하나의 변수(result)에 받는 경우
result = split_list(array)
print("함수 결과:", result)
print("result의 타입:", type(result))
print()

# 함수의 결과값을 여러 개의 변수에 받는 경우 (언패킹)
first, middle, last = split_list(array)
print("처음 값:", first)
print("중간 값:", middle)
print("마지막 값:", last)
print()

# 불필요한 값을 무시하는 방법
front, _, back = split_list(array)
print("처음 값:", front)
print("마지막 값:", back)

함수 결과: (1, [2, 3, 4], 5)
result의 타입: <class 'tuple'>

처음 값: 1
중간 값: [2, 3, 4]
마지막 값: 5

처음 값: 1
마지막 값: 5


## 2차원 리스트의 슬라이싱
arr2D에는 4x4 크기의 2차원 리스트가 담겨있습니다.

1차원 리스트 때와 마찬가지로 슬라이싱을 할 수 있지만, 슬라이싱 결과가 똑같이 2차원이어서\
가운데 두 개의 **세로줄**을 가져오기 위해서는 새로운 접근이 필요합니다.

코드 초반부의 arr2D를 출력하는 for문과 출력 결과를 참고하시길 바랍니다.

In [ ]:
arr2D = [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]

print("원본 리스트: ")
for row in arr2D:
  print(row)
print()

middle_rows = arr2D[1:3]
print("가운데 두 가로줄:", middle_rows)
print()

middle_columns = []
for row in arr2D:
  middle_columns.append(row[1:3])
print("가운데 두 세로줄:", middle_columns)

원본 리스트: 
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]

가운데 두 가로줄: [[5, 6, 7, 8], [9, 10, 11, 12]]

가운데 두 세로줄: [[2, 3], [6, 7], [10, 11], [14, 15]]


## NumPy의 슬라이싱
npArr2D에는 4x4 크기의 numpy array가 담겨있습니다.

기본 자료구조 리스트와는 다르게 **동시에 여러 차원의 인덱싱**이 가능해집니다.

리스트에서 특정 행과 특정 열의 값을 가져오려면 arr2D[1][2]과 같이 두 번의 인덱싱을 거쳐야했지만,\
np.array에서는 npArr2D[1, 2]처럼 **콤마**를 통해 한 번에 여러 차원의 접근할 수 있습니다.

이런 방식은 **슬라이싱**도 마찬가지입니다.\
이를 이용해서 궁극적으로는 **중앙 2x2의 값들**을 출력해보도록 합시다.

In [ ]:
import numpy as np

npArr2D = np.array([[ 1,  2,  3,  4],
                    [ 5,  6,  7,  8],
                    [ 9, 10, 11, 12],
                    [13, 14, 15, 16]])

print("원본 리스트: ", npArr2D, '', sep='\n')

middle_rows = npArr2D[1:3,:]
print("가운데 두 가로줄:", middle_rows, '', sep='\n')

middle_columns = npArr2D[:, 1:3]
print("가운데 두 세로줄:", middle_columns, '', sep='\n')

middle_2x2 = npArr2D[1:3, 1:3]
print("가운데 2x2 칸:", middle_2x2, '', sep='\n')

원본 리스트: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

가운데 두 가로줄:
[[ 5  6  7  8]
 [ 9 10 11 12]]

가운데 두 세로줄:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

가운데 2x2 칸:
[[ 6  7]
 [10 11]]



## Numpy array와 list의 연산 차이
Numpy의 array는 list와는 다르게 유용한 연산자들을 제공합니다.

list에서는 할 수 없었던 일들을 가능하게 해주어 여러 복잡한 과정들을 간결하게 해줍니다.


In [ ]:
listA = [1, 2, 3]
listB = [4, 5, 6]

# list와 상수간의 연산
# print(listA + 5) # 불가능
print(listA * 3)

# list와 list간의 연산
print(listA + listB)
# print(listA - listB, listA * listB, listA / listB) # 불가능

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [ ]:
arrA = np.array([1, 2, 3])
arrB = np.array([4, 5, 6])

# array와 상수간의 연산
print(arrA + 5)
print(arrA * 3)

# array와 array간의 연산
print(arrA + arrB)
print(arrA - arrB, arrA * arrB, arrA / arrB)

[6 7 8]
[3 6 9]
[5 7 9]
[-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


## 실습 종료 전 유의사항

※ 완료 시 우측 상단 프로필 옆 '**공유 - 액세스를 *링크가 있는 모든 사용자*로 전환**' 후 복사한 링크를 이루리 과제 란에 업로드 하세요.

<img src="https://lh3.googleusercontent.com/drive-viewer/AITFw-wjhSS5IXHGdbpyzA-GaPpZ0GDhNrgiRtgzIo2BdtRJwZlqVJzAg8GyEPRGM-46u8jQTXdQF6JN8AI1iHwz4xHFsnW2=w3838-h1937" height=300>

</br>

※ 추가로 상단 메뉴 '**파일 - 다운로드 - .ipynb**' 로 다운로드 후 첨부 파일로 업로드 하세요.

※ 즉, 과제의 텍스트란에는 링크를, 파일 첨부란에는 .ipynb 파일을 제출하십시오.