# 데이터분석프로그래밍 4주차 실습

## 실습 시작 전 유의사항

※ 상단 메뉴에서 '**파일 - 드라이브에 사본 저장**' 진행 후 시작하세요.\
※ 프로젝트 제목 뒤에 본인의 이름과 학번을 작성하세요. `ex) DataAnalysisProgramming_#01_202312345_정재호.ipynb`

## 실습 개요
- Numpy
  - array와 list의 연산 차이
  - Boolean Indexing
  - 크기 조절하기
- Pandas DataFrame

---

## Numpy array와 list의 연산 차이
Numpy의 array는 list와는 다르게 유용한 연산자들을 제공합니다.

list에서는 할 수 없었던 일들을 가능하게 해주어 여러 복잡한 과정들을 간결하게 해줍니다.


In [ ]:
listA = [1, 2, 3]
listB = [4, 5, 6]

# list와 상수간의 연산
# print(listA + 5) # 불가능
print(listA * 3)

# list와 list간의 연산
print(listA + listB)
# print(listA - listB, listA * listB, listA / listB) # 불가능

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

arrA = np.array([1, 2, 3])
arrB = np.array([4, 5, 6])

# array와 상수간의 연산
print(arrA + 5)
print(arrA * 3)

# array와 array간의 연산
print(arrA + arrB)
print(arrA - arrB, arrA * arrB, arrA / arrB)

[6 7 8]
[3 6 9]
[5 7 9]
[-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


## Numpy array의 Boolean Indexing
array는 위의 산술 연산자 뿐만 아니라 논리 연산자도 사용할 수 있습니다.

논리 연산의 결과로는 True와 False로 이뤄진 array가 생길 것입니다.

이것을 일종의 마스크(필터)처럼 이용하면 array의 특정 값만 뽑아낼 수 있습니다.\
이를 boolean 값을 이용한 인덱싱이라고 하여, Boolean Indexing이라고 부릅니다.

해당 실습에서, 각각의 값이 짝수가 맞는지를 나타내는 마스크를 만들어보고,\
그 마스크로 인덱싱을 하여 짝수 값들만 뽑아보도록 하겠습니다.

In [ ]:
import numpy as np

npArr = np.array([3, 6, 10, 2, 5, 9, 7, 11])

mask_even = npArr % 2 ==0
print("각 요소가 짝수인지 여부:", mask_even)

even_array = npArr[mask_even]
print("array의 짝수 값들:", even_array)

각 요소가 짝수인지 여부: [False  True  True  True False False False False]
array의 짝수 값들: [ 6 10  2]


## 크기 조절하기
array를 이용할 때에는, 때때로 연산을 위해 크기를 조절해야하는 경우가 생깁니다.

해당 실습에서는 array의 크기를 조절할 수 있는 여러 함수들을 소개하겠습니다.

- **`arr.shape`**: arr의 크기를 알려줍니다.
- **`np.resize(arr, shape)`**: arr가 shape 크기로 변경된 결과를 반환합니다.
- **`arr.reshape(shape)`**: arr가 shape 크기로 변형된 결과를 반환합니다.\
새로운 shape는 원본 shape에서 변형될 수 있는 값이어야 합니다.
- **`arr.flatten()`**: 다차원의 arr가 1차원으로 펼쳐진 결과를 반환합니다.

array의 shape는 특수하게 -1이라는 값을 사용할 수 있습니다.

shape에서 -1 값은 "자동으로 계산되어 채워지는 크기"를 의미합니다.

(2×△) 크기의 array로 만들고 싶은데 △ 값을 모르겠는 경우,\
-1로 채워주면 자동으로 알아내어 채워줍니다.

In [ ]:
import numpy as np

arr = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12]])
print("원본 크기:", arr.shape)
print()

arr1 = np.resize(arr, (4,4))
print("4x4로 확장:", arr1, '', sep='\n')

arr2 = arr.reshape(2,2,3)
print("2x2x3 크기:", arr2, '', sep='\n')

arr3 = arr.reshape(4,-1)
print("4x△ 크기:", arr3, '', sep='\n')

arr4 = arr.flatten()
print("flatten:", arr4, '', sep='\n')

arr5 = arr.reshape(-1)
print("-1을 이용한 1차원 array:", arr5, '', sep='\n')

원본 크기: (3, 4)

4x4로 확장:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]

2x2x3 크기:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

4x△ 크기:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

-1을 이용한 1차원 array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]



## Pandas DataFrame

pandas는 데이터프레임이라고 하는 2차원 배열의 자료구조를 다루는 기능들을 제공합니다.

이번 실습에서는 임의의 데이터프레임을 생성해보고, 이를 간단하게 수정해보는 코드를 작성해보겠습니다.

</br>

데이터프레임을 생성하는 대표적인 방법으로는, dict 자료구조를 사용하는 방식이 있습니다.

dict의 **키**가 각 열의 이름이 되고, **값**들은 해당 열의 데이터가 됩니다.

아래에 임의로 생성한 dict_data와 pd.DataFrame 함수를 이용하여 데이터프레임을 생성해봅시다.

In [ ]:
import numpy as np
import pandas as pd

dict_data = {
    '이름': ['철수', '영희', '민수', '지영', '태호'],
    '직장': ['서울', '부산', '대구', '서울', '대전'],
    '나이': [25, 22, 30, 28, 24],
    '직업': ['개발자', '디자이너', '마케터', '개발자', '분석가']
}

df = pd.DataFrame(dict_data)

print(f"열들의 이름: {df.columns}")
print(f"행들의 이름: {df.index}")
df

열들의 이름: Index(['이름', '직장', '나이', '직업'], dtype='object')
행들의 이름: RangeIndex(start=0, stop=5, step=1)


이름  직장  나이    직업
0  철수  서울  25   개발자
1  영희  부산  22  디자이너
2  민수  대구  30   마케터
3  지영  서울  28   개발자
4  태호  대전  24   분석가

dict_data의 key인 이름, 직장, 나이, 직업이 columns가 되었고, range(0, 5)가 index가 된 것을 확인할 수 있습니다.

index를 다른 것으로 변경하는 방법은 여러가지가 있지만, 지금은 데이터프레임의 **'이름'** 열을 index로 설정해보겠습니다.

이렇게 특정 열로 index를 설정하는 것은 **set_index** 함수를 통해 해결할 수 있습니다.

In [ ]:
df = df.set_index('이름')

df

직장  나이    직업
이름              
철수  서울  25   개발자
영희  부산  22  디자이너
민수  대구  30   마케터
지영  서울  28   개발자
태호  대전  24   분석가

이번에는 새로운 열을 추가하는 방법을 알아보겠습니다.

새로운 열은 dict에 새로운 값을 넣는 것과 유사하게 수행됩니다.

아래의 gender 값을 df의 '성별' 열에 추가해봅시다.

이때, 주의해야 할 것은 넣고자하는 데이터가 현재 데이터프레임의 크기와 같아야 한다는 것입니다.

In [ ]:
gender = ['남', '여', '남', '여', '남']

df['성별']=gender

df

직장  나이    직업 성별
이름                 
철수  서울  25   개발자  남
영희  부산  22  디자이너  여
민수  대구  30   마케터  남
지영  서울  28   개발자  여
태호  대전  24   분석가  남

다음으로는 데이터프레임의 특정 원소를 선택하는 실습입니다.

특정 원소를 선택하는 방법은 이름으로 선택하는 방법(loc), 위치 인덱스로 선택하는 방법(iloc), 이 두 가지가 있습니다.

각각 이름과 인덱스를 이용하여 한 번에 여러 개의 원소를 선택하거나 범위를 선택할 수도 있습니다.

지금은 loc을 이용하여 다음 작업을 수행해보도록 합시다.
- 민수 이후의 사람들은 1년전 정보라고 합니다. **민수부터 태호까지의 나이 정보를 1 더해줍시다.**
- 철수와 지영은 다니던 회사에서 퇴직했다고 합니다. **철수와 지영의 직장과 직업 정보를 빈 문자열 ""으로 설정합시다.**

In [ ]:
df.loc['민수':'태호','나이'] += 1
df.loc[['철수','지영'],['직장','직업']] = ""

df

직장  나이    직업 성별
이름                 
철수      25        남
영희  부산  22  디자이너  여
민수  대구  31   마케터  남
지영      29        여
태호  대전  25   분석가  남

## 실습 종료 전 유의사항

※ 완료 시 우측 상단 프로필 옆 '**공유 - 액세스를 *링크가 있는 모든 사용자*로 전환**' 후 복사한 링크를 이루리 과제 란에 업로드 하세요.

<img src="https://lh3.googleusercontent.com/drive-viewer/AITFw-wjhSS5IXHGdbpyzA-GaPpZ0GDhNrgiRtgzIo2BdtRJwZlqVJzAg8GyEPRGM-46u8jQTXdQF6JN8AI1iHwz4xHFsnW2=w3838-h1937" height=300>

</br>

※ 추가로 상단 메뉴 '**파일 - 다운로드 - .ipynb**' 로 다운로드 후 첨부 파일로 업로드 하세요.

※ 즉, 과제의 텍스트란에는 링크를, 파일 첨부란에는 .ipynb 파일을 제출하십시오.